---
version: "3"
services:

  server:
    image: haproxytechblog/grpc-sample-server
    build:
      context: ./sample
      dockerfile: server.dockerfile
    hostname: server
    container_name: server

  haproxy:
    image: haproxytech/haproxy-ubuntu:2.0.14
    environment:
      - HAPROXY_TARGET_IP
    hostname: haproxy
    container_name: haproxy
    volumes:
      - "./sample/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg"
      - "./sample/creds/haproxy.pem:/etc/haproxy/pem/haproxy.pem"
      - "./sample/creds/server.crt:/etc/haproxy/pem/server.crt"
    ports:
      - "3001:3001"

  client:
    image: haproxytechblog/grpc-sample-client
    build:
      context: ./sample
      dockerfile: client.dockerfile
    environment:
      - "SERVER_ADDRESS=haproxy:3001"
      - "TLS_CERT=haproxy.crt"
    hostname: client
    container_name: client
    entrypoint: [ "./client", "-s", "haproxy:3001" ]
    depends_on:
      - haproxy
