---
version: "3"
services:

  server:
    image: haproxytechblog/grpc-sample-server
    build:
      context: ./sample
      dockerfile: Dockerfile.server

  haproxy:
    image: haproxytech/haproxy-ubuntu:2.0.14
    environment:
    - HAPROXY_TARGET_IP
    volumes:
    - "./sample/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg"
    - "./sample/creds/haproxy.pem:/etc/haproxy/pem/haproxy.pem"
    - "./sample/creds/server.crt:/etc/haproxy/pem/server.crt"
    ports:
    - "3001:3001"

  client:
    image: haproxytechblog/grpc-sample-client
    build:
      context: ./sample
      dockerfile: Dockerfile.client
    environment:
    - "SERVER_ADDRESS=haproxy:3001"
    - "TLS_CERT=haproxy.crt"
    depends_on:
    - haproxy
